# Generated by Django 4.2.16 on 2026-04-16 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_add_hybrid_participation_and_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='program_pdf',
            field=models.FileField(blank=True, null=True, upload_to='programs/', verbose_name='Programme PDF'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_qr',
            field=models.ImageField(blank=True, null=True, upload_to='events/qrcodes/', verbose_name='QR code inscription'),
        ),
        migrations.AlterField(
            model_name='event',
            name='access_mode',
            field=models.CharField(choices=[('direct', 'Inscription directe'), ('validation', 'Avec validation')], default='direct', max_length=20, verbose_name="Mode d'accès (legacy)"),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_capacity_limited',
            field=models.BooleanField(default=False, verbose_name='Places limitées (legacy)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre max (legacy)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='mode',
            field=models.CharField(choices=[('online', 'En ligne'), ('onsite', 'Présentiel'), ('hybrid', 'Hybride')], default='online', max_length=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='platform',
            field=models.CharField(blank=True, choices=[('meet', 'Google Meet'), ('zoom', 'Zoom'), ('youtube', 'YouTube Live'), ('other', 'Autre')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='events.organizer', verbose_name='Intervenant'),
        ),
    ]
