# Generated by Django 4.2.16 on 2026-03-28 23:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('institution', models.CharField(max_length=200, verbose_name='Institution / Organisation')),
                ('role', models.CharField(max_length=150, verbose_name='Fonction / Poste')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('newsletter', models.BooleanField(default=False, verbose_name='Abonné aux actualités LASPAD')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('motivation', models.TextField(blank=True, verbose_name='Motivation / Message')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('calendar_invite_sent', models.BooleanField(default=False, verbose_name='Invitation calendrier envoyée')),
                ('confirmation_sent', models.BooleanField(default=False, verbose_name='Email de confirmation envoyé')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='Événement')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='registrations.participant', verbose_name='Participant')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-registered_at'],
                'unique_together': {('event', 'participant')},
            },
        ),
    ]
